### ISSUE TITLE
Add --no-progress feature

### ISSUE THREAD

**Issue by ksaffarian** [PowerShellOrg/cChoco#138] opened 2020-02-02 22:44 UTC
Hi
cChoco is probably is used heavily in CI/CD pipelines to bootstrap servers.
The default settings in Choco is to show alot of progress, like download percentage and more stuff, which is a bit annoying when you want to review deployment logs.
I suggest you add the option to PackageInstaller resource to turn on/off verbose and progress logging.
Thanks for the nice work.
Cheers

**Comment by pauby** [comment] 2020-02-03 14:05
This has already been completed and will be released in the next version.

Marking as a duplicate of #83

**Closed as completed by pauby** 2020-02-03 14:05 UTC
Labels: Duplicate Issue
