### ISSUE TITLE
cChocoInstaller fails to install Chocolatey, chocolatey folder already exists

### ISSUE THREAD

**Issue by mmeade-netapp** [PowerShellOrg/cChoco#152] opened 2021-02-05 23:00 UTC
**Describe the bug**
We have been using cChoco for about a year with good results.  This afternoon PDT, reports of failed deployments began which were caused by a failure to install chocolatey  by using the resource below:

        cChocoInstaller ChocoInstall
        {
            InstallDir = 'C:\ProgramData\chocolatey'
        }

The configuration, if ran with the verbose switch, detects that chocolatey isn't installed with the test script and the set script fails to install with the stated reason that it was already installed.    See attached image.

![Capture](https://user-images.githubusercontent.com/70663336/107097488-e7c92400-67c1-11eb-94f2-e26bb62c8a61.PNG)

We are using cChoco version 2.4.1.0

I was able to use the web download install script to install Chocolatey successfully, then the rest of the cChoco resource functioned as expected.

After a failed run of the Choco resource, a C:\ProgramData\chocolatey folder is created with a single PowerShell script.  Attached:

[install.ps1.txt](https://github.com/chocolatey/cChoco/files/5935744/install.ps1.txt)

**Comment by mmeade-netapp** [comment] 2021-02-05 23:22
Downloaded install.ps1 script has a function called Test-ChocolateyInstalled which returns true if chocolatey is installed or the chocolatey install folder exists and is not empty.  It returns true and the installer exists.  The default chocolatey folder isn’t empty because the downloaded script is placed here.

**Comment by gep13** [comment] 2021-02-06 07:04
This is a duplicate of this issue: https://github.com/chocolatey/cChoco/issues/151

I am going to close this one in favour of that one.

**Comment by ferventcoder** [comment] 2021-02-06 15:21
I like this title better and it more succinctly describes the problem. However the conversation has already started with the other issue and a better explanation of the security reasons why this was changed. There is also a workaround posted over there.

**Closed as completed by ferventcoder** 2021-02-06 15:21 UTC
Labels: Duplicate Issue
