### ISSUE TITLE
AppVeyor did not push new version

### ISSUE THREAD

**Issue by ferventcoder** [PowerShellOrg/cChoco#75] opened 2017-04-19 00:00 UTC

**Comment by ferventcoder** [comment] 2017-04-19 00:01
@lawrencegripper 

To combat this I wanted to see what was going on and added the notifications for appveyor to chocolatey-build-status at googlegroups dot com

**Comment by javydekoning** [comment] 2017-04-19 05:37
AppVeyor never started the deploy.ps1 script.

**Comment by lawrencegripper** [comment] 2017-04-19 05:59
Looks like the repo moving location has left appveyor a bit confused. I don't have access to the github repo settings anymore so I can't check and update the webhook stuff, will take a look now at appveyor to see if there is anything I can update that side. 

Attempted to add you to appveyor but need an email address, if you want to share one privately dm on twitter @lawrencegripper

**Comment by lawrencegripper** [comment] 2017-04-19 06:11
Sweet, looks like updating the appveyor build to point to the new repo location has done the trick. I've manually triggered a build for now, as it has missed the webhooks for the commits to master, and the build completed for v2.3.1.96. Output here: https://ci.appveyor.com/project/LawrenceGripper/cchoco/branch/master 

Would be worth validating if the hook settings in github need updating too or if it was just ignoring them because they came from a repo it didn't think it was building for. 

@ferventcoder checked your blog for email address, looks like your contact page 500's

**Comment by lawrencegripper** [comment] 2017-04-19 06:18
Looks like the repo move meant the appveyor didn't detect this as a build of master branch, thought it was from a fork. Created a PR to resolve this here: #76 Once the PR is merged we should see a deploy to powershell gallery. 

On the plus side it let me test the webhooks and appear to be triggering correctly so was just the appveyor changes required.

**Comment by ferventcoder** [comment] 2017-04-19 12:50
@lawrencegripper ferventcoder at gmail

**Comment by ferventcoder** [comment] 2017-04-19 12:56
@lawrencegripper you are now an admin on this repo.

**Comment by lawrencegripper** [comment] 2017-04-19 13:52
@ferventcoder now added to the appveyor with all the permissions, first time I've ever granted permissions through appveyor so apologies if I've got it wrong. 

Also build pushed updated module :)

![image](https://cloud.githubusercontent.com/assets/1939288/25183563/d4dc61b6-250f-11e7-863b-dc151598132f.png)

**Comment by ebekker** [comment] 2017-04-19 15:07
It looks like the 4th component of the version is now set to '0' (started with the prior build), but previously it was the AV build number (I'm guessing?).  Was that change by design?

**Comment by ferventcoder** [comment] 2017-04-19 15:55
@ebekker no idea - just coming into this.

**Closed as completed** 2017-04-27 22:49 UTC
Labels: 4 - Done, Build Automation
