### ISSUE TITLE
cChocoInstaller changes $env:temp

### ISSUE THREAD

**Issue by mh185277** [PowerShellOrg/cChoco#137] opened 2020-01-31 15:00 UTC
After install by
cChocoInstaller InstallChoco
{
    InstallDir = "$env:ALLUSERSPROFILE\Chocolatey"
}
The $env:temp is changed from 
C:\Windows\TEMP to C:\Windows\system32\config\systemprofile\AppData\Local\Temp\

***The operating system the target node is running***
OsName : Microsoft Windows 10 Enterprise LTSC
OsOperatingSystemSKU : 125
OsArchitecture : 64-bit
WindowsVersion : 1809
WindowsBuildLabEx : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage : en-US
OsMuiLanguages : {en-US}

***Version and build of PowerShell the target node is running***
Name Value

PSVersion 5.1.17763.771
PSEdition Desktop
PSCompatibleVersions {1.0, 2.0, 3.0, 4.0...}
BuildVersion 10.0.17763.771
CLRVersion 4.0.30319.42000
WSManStackVersion 3.0
PSRemotingProtocolVersion 2.3
SerializationVersion 1.1.0.1

**Comment by pauby** [comment] 2020-05-21 17:03
I'm not able to reproduce this in a Windows Server 2016 Vagrant environment using your code above.

**Comment by pauby** [comment] 2020-05-21 17:28
Just tried this on a Windows 10 Enterprise Build 18362 and I'm still not able to reproduce it.

**Comment by pauby** [comment] 2021-07-16 10:28
I'm going to go ahead and close this now. We can always reopen it later if we get more information that allows us to reproduce.

**Closed as completed by pauby** 2021-07-16 10:28 UTC
Labels: Invalid / Not Issue / No repro / Not Implementing
